services:
  devops1:
    build: .
    image: devops1:latest
    container_name: devops1-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - TZ=Asia/Kathmandu
    stop_grace_period: 5s
